routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'MainController@index')->name('main');


Route::get('shop', 'ShopController@shop')->name('shop');
Route::get('shop_', 'ShopController@shop_')->name('shop_');
Route::get('shop__', 'ShopController@shop__')->name('shop__');

Route::resource('pages', 'PageController')->only('show');

Route::get('news/mini', 'NewsController@mini')->name('news.mini');
Route::get('news/mini_basic', 'NewsController@mini_basic')->name('news.mini_basic');
Route::resource('news', 'NewsController')->only('index', 'show');

Route::get('articles/mini', 'BlogController@mini')->name('articles.mini');
Route::resource('articles', 'BlogController')->only('index', 'show');


/*auth*/
Route::middleware(['auth'])->group(function () {

    Route::get('/home', function () {
        return view('frontend.auth.home');
    })->name('home');

    Route::resource('user', 'UserController')->only('show','edit', 'update');

    Route::post('comments/store/{article}', 'BlogController@add_comments')->name('comments.store');
    Route::post('comments/like/{comment}', 'BlogController@like_comments')->name('comments.like');
    Route::post('comments/update/{comment}', 'BlogController@update_comments')->name('comments.update');
    Route::post('comments/delete/{comment}', 'BlogController@delete_comments')->name('comments.delete');
});


#region Admin
Route::group(['prefix' => 'admin', 'middleware' => [
    'auth',
    'role:moderator'
], 'namespace' => 'Admin', 'as' => 'admin.'], function () {


    /*default*/
    Route::get('/', function (){
        return view('admin.main');
    })->name('main');
    Route::resource('users', 'UserController')->only('index', 'edit'); //*
    Route::resource('sessions', 'SessionController')->only('index'); //*


    /*E-commerce*/
    Route::get('categories/place', 'CategoryController@place')->name('categories.place'); //*
    Route::resource('categories', 'CategoryController')->only('index', 'edit'); //*

    Route::resource('products', 'ProductController')->only('index', 'edit', 'show'); //*
    Route::resource('orders', 'OrderController')->only('index', 'edit');
    Route::resource('payments', 'PaymentController')->only('index', 'edit');
    Route::resource('carts', 'CartController')->only('index', 'edit');


    /*Content*/
    Route::resource('pages', 'PageController')->only('index', 'edit', 'show');
    Route::resource('menus', 'MenuController')->only('index', 'edit');
    Route::resource('news', 'NewController')->only('index', 'edit', 'show');

    Route::resource('article-categories', 'ArticleCategoryController')->only('index', 'edit'); //*
    Route::get('article-categories/place', 'ArticleCategoryController@place')->name('article-categories.place'); //*

    Route::resource('articles', 'ArticleController')->only('index', 'edit', 'show');
    Route::resource('texts', 'TextController')->only('index', 'edit', 'show');


    /*Settings*/
    Route::resource('settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('api_settings', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('roles', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');
    Route::resource('permissions', 'SettingController')->middleware('role:admin')->only('index', 'edit', 'show');


    /*misc*/
    Route::get('documentation', function (){
        echo "documentation";
    })->name('documentation');

    Route::resource('admin_settings', 'AdminSettingController')->middleware('role:owner')->only('index');

});
#endregion

resources/views/frontend/partials/_footer.blade.php
<div class="footer" style="background-color: #1C2519;">
    <div class="text-center">
        <p style="padding: 0; margin: 0;">
            <strong><img src="{{ asset('favicon.ico') }}" width="35" height="35" style="margin-right: 5px;"> {{ config('app.name', 'MineStartProject') }} /  v0.0.1 (alpha)</strong>
        </p>
    </div>
</div>

resources/views/frontend/partials/_nav.blade.php
<nav id="nav" class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            <img src="{{ asset('favicon.ico') }}" width="35" height="35"
                 style="margin-right: 5px;"> {{ config('app.name', 'MineStartProject') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('main') }}">{{ __('HOME') }}</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ __('SHOP') }} <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('shop') }}">
                            {{ __('SHOP WITH CART') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('shop_') }}">
                            {{ __('SHOP WITH OUT CART') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('shop__') }}">
                            {{ __('CATALOG') }}
                        </a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ __('BLOG') }} <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('articles.index') }}">
                            {{ __('DEFAULT') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('articles.mini') }}">
                            {{ __('COMPACT') }}
                        </a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ __('NEWS') }} <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('news.index') }}">
                            {{ __('DEFAULT') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('news.mini') }}">
                            {{ __('COMPACT') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('news.mini_basic') }}">
                            {{ __('MINI') }}
                        </a>
                    </div>
                </li>

                @if(count($pages) >= 1)
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ __('PAGES') }} <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            @foreach($pages as $page)
                                <a class="dropdown-item" href="{{ route('pages.show', $page->slug) }}">
                                    {{ __($page->title) }}
                                </a>
                            @endforeach
                        </div>
                    </li>
                @endif

                <li class="nav-item">
                    <a class="nav-link" href="#">|</a>
                </li>
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('LOGIN') }}</a>
                    </li>
                    <li class="nav-item">
                        @if (Route::has('register'))
                            <a class="nav-link" href="{{ route('register') }}">{{ __('REGISTER') }}</a>
                        @endif
                    </li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            @if(Auth::user()->hasRole('admin'))
                                <a class="dropdown-item" href="{{ route('admin.main') }}">
                                    {{ __('Admin') }}
                                </a>
                                <hr>
                            @endif

                            <a class="dropdown-item" href="{{ route('user.show', Auth::user()->id) }}">
                                {{ __('Profile') }}
                            </a>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                  style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/frontend/partials/_style.blade.php
<style>
    #circle-div{
        position: fixed;
        background-color: #151E12;
        width: 100%;
        height: 100vh;
        z-index: 10000;
    }

    #circle {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        width: 150px;
        height: 150px;
    }

    .loader {
        width: calc(100% - 0px);
        height: calc(100% - 0px);
        border: 8px solid #6BA73B;
        border-top: 8px solid #1C2519;
        border-radius: 50%;
        animation: rotate 5s linear infinite;
    }

    @keyframes rotate {
        100% {transform: rotate(360deg);}
    }

    *{
        transition: all 0.2s ease;
    }

    html, body {
        background-color: #151E12;
        color: #7BC043;
        font-family: 'Nunito', sans-serif;
        font-weight: 200;
        height: 100vh;
        margin: 0;
    }

    ::-webkit-scrollbar{
        width:6px;
    }
    ::-webkit-scrollbar-thumb{
        border-width:1px 1px 1px 2px;
        border-color: #777;
        background-color: #18621a;
    }
    ::-webkit-scrollbar-thumb:hover{
        border-width: 1px 1px 1px 2px;
        border-color: #555;
        background-color: #7BC043;
    }
    ::-webkit-scrollbar-track{
        border-width:0;
        border-left: solid 1px #151E12;
        background-color: #151E12;
    }
    ::-webkit-scrollbar-track:hover{
        border-left: solid 1px #151E12;
        background-color: #1C2519;
    }

    .card-shop{
        transition: all 0.5s ease;
    }
    .card-shop:hover{
        transform: scale(1.02);
        box-shadow: 0px 0px 30px rgba(123, 192, 67, 0.26);
    }

    .list-group-item {
        position: relative;
        display: block;
        padding: 0px;
        margin-bottom: -1px;
        background-color: #1C2519;
        border: 1px solid #131d10;
    }

    .modal-content {
        position: relative;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: column;
        flex-direction: column;
        width: 100%;
        pointer-events: auto;
        background-color: #151E12;
        background-clip: padding-box;
        border: 1px solid #1C2519;
        border-radius: .3rem;
        outline: 0;
    }
    .modal-header {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-align: start;
        align-items: flex-start;
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 1rem;
        border-bottom: 1px solid #1C2519;
        border-top-left-radius: .3rem;
        border-top-right-radius: .3rem;
    }

    .form-control, .form-control:active, .form-control:hover, .form-control:focus {
        color: #7BC043;
        background-color: #30392D;
        border: 1px solid #80906f;
        outline: none;

    }
    .form-control:active, .form-control:focus {
        box-shadow: 0 0 0 0.2rem rgba(128, 144, 111, 0.31);
    }

    a {
        color: #7BC043 !important;
    }

    a:hover {
        color: #b1f946 !important;
    }

    .card {
        background-color: #1C2519;
        border: 1px solid rgba(0, 0, 0, 0.125);
        border-radius: 0.25rem;
    }

    .navbar-laravel {
        background-color: #1C2519;
        color: #7BC043 !important;
    }

    .dropdown-menu {
        background-color: #1C2519;
        border: 1px solid rgba(0, 0, 0, 0.15);
        border-radius: 0.25rem;
    }

    .nav-item:hover .dropdown-menu {
        top: 90% !important;
        display: block !important;
    }

    .dropdown-menu:hover {
        top: 90% !important;
        display: block !important;
    }

    .dropdown-item:hover {
        background-color: #2D362A;
    }

    .full-height {
        height: 100vh;
    }

    .flex-center {
        align-items: center;
        display: flex;
        justify-content: center;
    }

    .position-ref {
        position: relative;
    }

    .top-right {
        position: absolute;
        right: 10px;
        top: 18px;
    }

    .content {
        text-align: center;
    }

    .title {
        font-size: 84px;
    }
    .img-card:hover + .card-info{
        margin-top: -10px !important;
    }
    .back-to-top {
        cursor: pointer;
        position: fixed;
        bottom: 20px;
        right: 20px;
        display:none;
    }



    .comment-box {
        margin-top: 30px !important;
        width: 100%;
    }

    .comment-box img {
        width: 50px;
        height: 50px;
    }
    .comment-box .media-left {
        padding-right: 10px;
        width: 65px;
    }
    .comment-box .media-body p {
        border: 1px solid #2c3529;
        padding: 10px;
    }
    .comment-box .media-body .media p {
        margin-bottom: 0;
    }
    .comment-box .media-heading {
        background-color: #151E12;
        border: 1px solid #2c3529;
        padding: 7px 10px;
        position: relative;
        margin-bottom: -1px;
    }
    .comment-box .media-heading:before {
        content: "";
        width: 12px;
        height: 12px;
        background-color: #151E12;
        border: 1px solid #151E12;
        border-width: 1px 0 0 1px;
        -webkit-transform: rotate(-45deg);
        transform: rotate(-45deg);
        position: absolute;
        top: 10px;
        left: -6px;
    }

    .page-link {
        background-color: #1C2519;
        border: 1px solid #7BC043;
    }

    .page-item.active .page-link {
        z-index: 1;
        color: #fff;
        background-color: #7BC043;
        border-color: #7BC043;
    }

    .page-item.disabled .page-link {
        color: #6c757d;
        background-color: #333;
        border-color: #7BC043;
    }

    .page-link:hover {
        background-color: #576054;
        border-color: #7BC043;
    }
</style>

resources/views/frontend/partials/_up.blade.php
<a id="back-to-top" href="#" class="btn btn-outline-secondary btn-sm back-to-top" role="button"><i class="fas fa-arrow-circle-up"></i></a>